package ingenieriasoft2proyecto.Vistas;

import ingenieriasoft2proyecto.Modelos.Producto;
import ingenieriasoft2proyecto.VentaControler;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import ingenieriasoft2proyecto.Modelos.DetalleVenta;
import ingenieriasoft2proyecto.Modelos.Venta;
import ingenieriasoft2proyecto.VentaMVC;
import java.util.Date;

public class PrincipalAle extends javax.swing.JFrame {
    public DefaultTableModel tablaProductos;
    public DefaultTableModel tablaFactura;
    ArrayList<Producto> productos;
    ArrayList<DetalleVenta> factura;
    int idProducto;
    DetalleVenta detalleVenta;
    private VentaMVC.Controler vc;
    Venta venta;
            
    public PrincipalAle() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        tablaProductos = (DefaultTableModel) jTableProductos.getModel();
        tablaFactura = (DefaultTableModel) jTableFactura.getModel();
        //jTableProductos.setModel(tablaProductos);
        productos = new ArrayList<>();
        factura = new ArrayList<>();
        vc = new VentaControler(this);
        venta = new Venta();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelVenta = new javax.swing.JPanel();
        jPanelProductos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jTextFieldBuscarProducto = new javax.swing.JTextField();
        jButtonAgregarFactura = new javax.swing.JButton();
        jPanelFactura = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFactura = new javax.swing.JTable();
        jButtonCancelar = new javax.swing.JButton();
        jButtonQuitar = new javax.swing.JButton();
        jButtonVender = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(204, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, -1, -1));

        jPanelProductos.setBackground(new java.awt.Color(204, 204, 204));
        jPanelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null},
                {"", null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Stock", "Cantidad requerida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductos.setRowHeight(25);
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        jPanelProductos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 575, 400));

        jTextFieldBuscarProducto.setText("Ingrese el nombre del producto");
        jTextFieldBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarProductoActionPerformed(evt);
            }
        });
        jTextFieldBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarProductoKeyPressed(evt);
            }
        });
        jPanelProductos.add(jTextFieldBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 11, 428, 37));

        jButtonAgregarFactura.setBackground(new java.awt.Color(0, 102, 51));
        jButtonAgregarFactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAgregarFactura.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarFactura.setText("Agregar a la factura");
        jButtonAgregarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarFacturaActionPerformed(evt);
            }
        });
        jPanelProductos.add(jButtonAgregarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, 35));

        jPanelFactura.setBackground(new java.awt.Color(204, 204, 255));
        jPanelFactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad requerida", "Sub total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFactura.setRowHeight(25);
        jScrollPane2.setViewportView(jTableFactura);

        jPanelFactura.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, 575, 400));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelFactura.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        jButtonQuitar.setBackground(new java.awt.Color(204, 0, 0));
        jButtonQuitar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonQuitar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuitar.setText("Quitar");
        jButtonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarActionPerformed(evt);
            }
        });
        jPanelFactura.add(jButtonQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 113, -1));

        jButtonVender.setBackground(new java.awt.Color(0, 102, 51));
        jButtonVender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonVender.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVender.setText("Vender");
        jButtonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderActionPerformed(evt);
            }
        });
        jPanelFactura.add(jButtonVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 502, 113, 35));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Factura");
        jPanelFactura.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 34, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Total: $");
        jPanelFactura.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTotal.setText("0.0");
        jPanelFactura.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 50, -1));

        javax.swing.GroupLayout jPanelVentaLayout = new javax.swing.GroupLayout(jPanelVenta);
        jPanelVenta.setLayout(jPanelVentaLayout);
        jPanelVentaLayout.setHorizontalGroup(
            jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentaLayout.createSequentialGroup()
                .addComponent(jPanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVentaLayout.setVerticalGroup(
            jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
            .addComponent(jPanelFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Venta", jPanelVenta);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1200, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarActionPerformed
        if(jTableFactura.getSelectedRow() != -1){
            int idInsumo = factura.get(jTableFactura.getSelectedRow()).getIdInsumo();
            int cantidadRequerida = factura.get(jTableFactura.getSelectedRow()).getCantidad();
            factura.remove(jTableFactura.getSelectedRow());
            Iterator<Producto> it = productos.iterator();
            Producto producto = new Producto();
            
            while(it.hasNext()){
                //Ver si no se salta el primero
                producto = it.next();
                //Ver si modifica el iterator
                if(producto.getId() == idInsumo){
                    producto.setStock(producto.getStock() + cantidadRequerida);
                    break;
                }
                else
                    System.out.println("Error Fatal: no lo encontro el prodcuto\n");
            }
            float total =  Float.parseFloat(jLabelTotal.getText());
            tablaFactura.setRowCount(0);
            String nombreInsumo = "Error";
            int fila=0;
            for(DetalleVenta dv : factura){
                tablaFactura.addRow(new Object[3]);
                for(Producto p: productos){
                    if(p.getId() == dv.getIdInsumo()){
                        nombreInsumo = p.getNombre();
                        break;
                    }
                    else
                        System.out.println("Error Fatal, no se encontro el insumo\n");
                }
                jTableFactura.setValueAt(nombreInsumo,fila,0);
                jTableFactura.setValueAt(dv.getCantidad(), fila,1);
                jTableFactura.setValueAt(dv.getSubtotal(), fila,2);
                total -= dv.getSubtotal();
            }
            jLabelTotal.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_jButtonQuitarActionPerformed

    private void jTextFieldBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarProductoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldBuscarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarProductoKeyPressed
        tablaProductos.setRowCount(0);
        productos = vc.obtenerTodo();
        
        String buscar = jTextFieldBuscarProducto.getText();
        buscar = buscar.toUpperCase();
        int i;
        int fila = 0;
        for (Producto p : productos){
            String buscando = p.getNombre();
            buscando=buscando.toUpperCase();
            buscando = buscando.toUpperCase();
            
            if(buscando.contains(buscar)){
                tablaProductos.addRow(new Object[4]);
                jTableProductos.setValueAt(p.getId(),fila,0);
                jTableProductos.setValueAt(p.getNombre(),fila,1);
                jTableProductos.setValueAt(p.getPrecio(),fila,2);
                jTableProductos.setValueAt(p.getStock(), fila,3);
                fila++;
            }
        }
    }//GEN-LAST:event_jTextFieldBuscarProductoKeyPressed

    private void jButtonAgregarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarFacturaActionPerformed
        if(jTableProductos.getSelectedRow() != -1){
            int stock = (int) jTableProductos.getValueAt(jTableProductos.getSelectedRow(),3);
            int cantidadPedida = (int) jTableProductos.getValueAt(jTableProductos.getSelectedRow(),4);
            if(cantidadPedida <= stock){
                Iterator<Producto> it = productos.iterator();
                Producto producto = new Producto();
                while(it.hasNext()){
                    //Ver si no se salta el primero
                    producto = it.next();
                    //Ver si modifica el iterator
                    if(producto.getId() == idProducto){
                        producto.setStock(stock - cantidadPedida);
                        break;
                    }
                    else
                        System.out.println("Error Fatal: no lo encontro el prodcuto\n");
                }
                DetalleVenta detalleVenta = new DetalleVenta();
                detalleVenta.setCantidad(cantidadPedida);
                detalleVenta.setIdInsumo(producto.getId());
                detalleVenta.setSubtotal(producto.getPrecio()*cantidadPedida);
                factura.add(detalleVenta);
                
                tablaProductos.setRowCount(0);
                String nombreInsumo = "Error";
                int fila=0;
                float total =  (float)0.0;
                for(DetalleVenta dv : factura){
                    tablaFactura.addRow(new Object[3]);
                    for(Producto p: productos){
                        if(p.getId() == dv.getIdInsumo()){
                            nombreInsumo = p.getNombre();
                            break;
                        }
                        else
                            System.out.println("Error Fatal, no se encontro el insumo\n");
                    }
                    jTableFactura.setValueAt(nombreInsumo,fila,0);
                    jTableFactura.setValueAt(dv.getCantidad(), fila,1);
                    jTableFactura.setValueAt(dv.getSubtotal(), fila,2);
                    total += dv.getSubtotal();
                }
                jLabelTotal.setText(String.valueOf(total));
            }
        }
    }//GEN-LAST:event_jButtonAgregarFacturaActionPerformed

    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked
        idProducto = (int) jTableProductos.getValueAt(jTableProductos.getSelectedRow(),0);
    }//GEN-LAST:event_jTableProductosMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        //Hay otra forma de hacerlo sin llamar a la base de datos
        productos.removeAll(productos);
        limpiar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderActionPerformed
        if(!factura.isEmpty()){
            venta.setDetalles(factura);
            Date fechaHoy = new Date();
            venta.setFecha(fechaHoy);
            
        }
    }//GEN-LAST:event_jButtonVenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalAle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarFactura;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonQuitar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanelFactura;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JPanel jPanelVenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableFactura;
    public javax.swing.JTable jTableProductos;
    public javax.swing.JTextField jTextFieldBuscarProducto;
    // End of variables declaration//GEN-END:variables
    public void limpiar(){
        productos = vc.obtenerTodo();
        tablaProductos.setRowCount(0);
        int fila = 0;
        for(Producto p: productos){
            tablaProductos.addRow(new Object[4]);
            jTableProductos.setValueAt(p.getId(),fila,0);
            jTableProductos.setValueAt(p.getNombre(),fila,1);
            jTableProductos.setValueAt(p.getPrecio(),fila,2);
            jTableProductos.setValueAt(p.getStock(), fila,3);
            fila++;
        }
        
        factura.removeAll(factura);
        tablaFactura.setRowCount(0);
        jLabelTotal.setText("0.0");
    }
}
