/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Main.Funciones;
import Controllers.GestionarReparacionesController;
import Interfaces.GestionarReparacionesMVP;
import Modelos.DetalleVenta;
import Modelos.Equipo;
import Modelos.Presupuesto;
import Modelos.Producto;
import Modelos.Reparacion;
import Modelos.Tarea;
import Modelos.Venta;
import Controllers.VentaControler;
import Interfaces.VentaMVC;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Note250
 */
public class Principal extends javax.swing.JFrame implements GestionarReparacionesMVP.View, VentaMVC.View{
    public DefaultTableModel modeloTablaSeleccionarPresupuestos;
    private GestionarReparacionesMVP.Controller mController;
    private List<Tarea> listTareas;
    private List<Equipo> equipos;
    private Presupuesto presupuesto;
    private Equipo equipo;
    private Reparacion reparacion;
    public DefaultTableModel tablaProductos;
    public DefaultTableModel tablaFactura;
    ArrayList<Producto> productos;
    ArrayList<DetalleVenta> factura;
    int idProducto;
    DetalleVenta detalleVenta;
    private VentaMVC.Controler vc;
    Venta venta;
    /**
     * Creates new form Principal
     */
    public Principal(int tipo) {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextF1GestionRepBuscarEquipos.setToolTipText("Ingrese el nombre del equipo a buscar");
        mController = new GestionarReparacionesController(this);
        //mController.mostarPresupuestos();
        equipos =mController.obtenerEquipos();
        DefaultTableModel model = (DefaultTableModel) jTableGestRepEquiposParaReparar.getModel();
        model.setRowCount(0);
        for(Equipo e : equipos){
            Object[] nuevoEquipo = {e.getModelo(),e.getMarca(),e.getFechaRecepcion(),e.getEstado(),e.getId()};
            model.addRow(nuevoEquipo);
        }
        tablaProductos = (DefaultTableModel) jTableProductos.getModel();
        tablaFactura = (DefaultTableModel) jTableFactura.getModel();
        //jTableProductos.setModel(tablaProductos);
        productos = new ArrayList<>();
        factura = new ArrayList<>();
        vc = new VentaControler(this);
        venta = new Venta();
        limpiar();
        switch(tipo){
            case 1:
            {
                
                break;
            }
            case 2:
            {
                jTabbedPane1.remove(1);
                break;
            }
            case 3:
            {
                jTabbedPane1.remove(0);
            }
        }
        //capturo los modelos de la pestaña gestionar reparaciones
        modeloTablaSeleccionarPresupuestos= (DefaultTableModel) jTableGestRepEquiposParaReparar.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGestRepEquiposParaReparar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAltaTarea = new javax.swing.JButton();
        jButtonEliminarTarea = new javax.swing.JButton();
        jButtonModificarTarea = new javax.swing.JButton();
        jButtonFinalizarReparacion = new javax.swing.JButton();
        jTextF2Falla = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelFechaIngreso = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableGestRepListadoTareasSeleccionadas = new javax.swing.JTable();
        jTextFiEstadoRecepcionEqui = new javax.swing.JTextField();
        jTextFiEstadoEquipo = new javax.swing.JTextField();
        jTextFMarca = new javax.swing.JTextField();
        jTextFModelo = new javax.swing.JTextField();
        jTextF1GestionRepBuscarEquipos = new javax.swing.JTextField();
        jPanelVenta = new javax.swing.JPanel();
        jPanelProductos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jTextFieldBuscarProducto = new javax.swing.JTextField();
        jButtonAgregarFactura = new javax.swing.JButton();
        jPanelFactura = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableFactura = new javax.swing.JTable();
        jButtonCancelar = new javax.swing.JButton();
        jButtonQuitar = new javax.swing.JButton();
        jButtonVender = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableGestRepEquiposParaReparar1 = new javax.swing.JTable();
        jTextF2Falla1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFModelo1 = new javax.swing.JTextField();
        jTextFMarca1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFiEstadoRecepcionEqui1 = new javax.swing.JTextField();
        jTextFiEstadoEquipo1 = new javax.swing.JTextField();
        jLabelFechaIngreso1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableGestRepEquiposParaReparar2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jTableGestRepEquiposParaReparar.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jTableGestRepEquiposParaReparar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Marca", "Fecha Ingreso", "Estado", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGestRepEquiposParaReparar.setColumnSelectionAllowed(true);
        jTableGestRepEquiposParaReparar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGestRepEquiposParaRepararMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableGestRepEquiposParaReparar);
        jTableGestRepEquiposParaReparar.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel1.setText("Modelo");

        jLabel2.setText("SELECCIONE UN EQUIPO");

        jButtonAltaTarea.setText("Alta Tarea");
        jButtonAltaTarea.setEnabled(false);
        jButtonAltaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaTareaActionPerformed(evt);
            }
        });

        jButtonEliminarTarea.setText("Eliminar Tarea");
        jButtonEliminarTarea.setEnabled(false);

        jButtonModificarTarea.setText("Modificar Tarea");
        jButtonModificarTarea.setEnabled(false);

        jButtonFinalizarReparacion.setText("Finalizar Reparación");
        jButtonFinalizarReparacion.setEnabled(false);

        jTextF2Falla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF2FallaActionPerformed(evt);
            }
        });

        jLabel3.setText("Marca");

        jLabel4.setText("Fecha de Ingreso");

        jLabel5.setText("Falla");

        jLabelFechaIngreso.setText("alguna fecha ");

        jLabel7.setText("Estado");

        jLabel8.setText("Estado recepcion");

        jTableGestRepListadoTareasSeleccionadas.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jTableGestRepListadoTareasSeleccionadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "garantia", "Detalle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableGestRepListadoTareasSeleccionadas);
        if (jTableGestRepListadoTareasSeleccionadas.getColumnModel().getColumnCount() > 0) {
            jTableGestRepListadoTareasSeleccionadas.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableGestRepListadoTareasSeleccionadas.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableGestRepListadoTareasSeleccionadas.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        jTextF1GestionRepBuscarEquipos.setText("Ingrese el nombre del equipo a buscar");
        jTextF1GestionRepBuscarEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextF1GestionRepBuscarEquiposMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextF1GestionRepBuscarEquiposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextF1GestionRepBuscarEquiposMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextF1GestionRepBuscarEquiposMouseReleased(evt);
            }
        });
        jTextF1GestionRepBuscarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF1GestionRepBuscarEquiposActionPerformed(evt);
            }
        });
        jTextF1GestionRepBuscarEquipos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextF1GestionRepBuscarEquiposKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAltaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jButtonModificarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButtonEliminarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(116, 116, 116)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextF2Falla, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(163, 163, 163)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFiEstadoEquipo)
                                .addComponent(jTextFiEstadoRecepcionEqui)
                                .addComponent(jLabelFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                            .addComponent(jTextF1GestionRepBuscarEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonFinalizarReparacion)
                        .addGap(31, 31, 31))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAltaTarea, jButtonEliminarTarea, jButtonModificarTarea});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextF1GestionRepBuscarEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextF2Falla, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFiEstadoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFiEstadoRecepcionEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAltaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFinalizarReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAltaTarea, jButtonEliminarTarea, jButtonModificarTarea});

        jTabbedPane1.addTab("Gestionar Reparaciones", jPanel1);

        jPanelProductos.setBackground(new java.awt.Color(204, 204, 204));
        jPanelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null},
                {"", null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Stock", "Cantidad requerida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductos.setRowHeight(25);
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        jPanelProductos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 575, 400));

        jTextFieldBuscarProducto.setText("Ingrese el nombre del producto");
        jTextFieldBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarProductoActionPerformed(evt);
            }
        });
        jTextFieldBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarProductoKeyPressed(evt);
            }
        });
        jPanelProductos.add(jTextFieldBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 11, 428, 37));

        jButtonAgregarFactura.setBackground(new java.awt.Color(0, 102, 51));
        jButtonAgregarFactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAgregarFactura.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarFactura.setText("Agregar a la factura");
        jButtonAgregarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarFacturaActionPerformed(evt);
            }
        });
        jPanelProductos.add(jButtonAgregarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, 35));

        jPanelFactura.setBackground(new java.awt.Color(204, 204, 255));
        jPanelFactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad requerida", "Sub total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFactura.setRowHeight(25);
        jScrollPane4.setViewportView(jTableFactura);

        jPanelFactura.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, 575, 400));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelFactura.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        jButtonQuitar.setBackground(new java.awt.Color(204, 0, 0));
        jButtonQuitar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonQuitar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuitar.setText("Quitar");
        jButtonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarActionPerformed(evt);
            }
        });
        jPanelFactura.add(jButtonQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 110, 30));

        jButtonVender.setBackground(new java.awt.Color(0, 102, 51));
        jButtonVender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonVender.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVender.setText("Vender");
        jButtonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderActionPerformed(evt);
            }
        });
        jPanelFactura.add(jButtonVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Factura");
        jPanelFactura.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 34, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Total: $");
        jPanelFactura.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, -1));

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTotal.setText("0.0");
        jPanelFactura.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 50, -1));

        javax.swing.GroupLayout jPanelVentaLayout = new javax.swing.GroupLayout(jPanelVenta);
        jPanelVenta.setLayout(jPanelVentaLayout);
        jPanelVentaLayout.setHorizontalGroup(
            jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentaLayout.createSequentialGroup()
                .addComponent(jPanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVentaLayout.setVerticalGroup(
            jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Venta", jPanelVenta);

        jTableGestRepEquiposParaReparar1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jTableGestRepEquiposParaReparar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Marca", "Fecha Ingreso", "Estado", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGestRepEquiposParaReparar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGestRepEquiposParaReparar1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableGestRepEquiposParaReparar1);
        jTableGestRepEquiposParaReparar1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jTextF2Falla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF2Falla1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Falla");

        jLabel11.setText("Marca");

        jLabel12.setText("Modelo");

        jLabel13.setText("Fecha de Ingreso");

        jLabel14.setText("Estado");

        jLabel15.setText("Estado recepcion");

        jLabelFechaIngreso1.setText("alguna fecha ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(116, 116, 116)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextFModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextFMarca1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextF2Falla1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(163, 163, 163)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFiEstadoEquipo1)
                        .addComponent(jTextFiEstadoRecepcionEqui1)
                        .addComponent(jLabelFechaIngreso1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                    .addGap(24, 24, 24)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(204, 204, 204)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextF2Falla1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFechaIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFiEstadoEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFMarca1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFiEstadoRecepcionEqui1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(205, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Equipos reparados", jPanel2);

        jTableGestRepEquiposParaReparar2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jTableGestRepEquiposParaReparar2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Marca", "Fecha Ingreso", "Estado", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGestRepEquiposParaReparar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGestRepEquiposParaReparar2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableGestRepEquiposParaReparar2);
        jTableGestRepEquiposParaReparar2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Equipos entregados", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderActionPerformed
        if(!factura.isEmpty()){
            venta.setDetalles(factura);
            Date fechaHoy = new Date();
            venta.setFecha(fechaHoy);
            vc.insertarVenta(venta);
        }
    }//GEN-LAST:event_jButtonVenderActionPerformed

    private void jButtonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarActionPerformed
        if(jTableFactura.getSelectedRow() != -1){
            int idInsumo = factura.get(jTableFactura.getSelectedRow()).getIdInsumo();
            int cantidadRequerida = factura.get(jTableFactura.getSelectedRow()).getCantidad();
            factura.remove(jTableFactura.getSelectedRow());
            Iterator<Producto> it = productos.iterator();
            Producto producto = new Producto();

            while(it.hasNext()){
                //Ver si no se salta el primero
                producto = it.next();
                //Ver si modifica el iterator
                if(producto.getId() == idInsumo){
                    producto.setStock(producto.getStock() + cantidadRequerida);
                    break;
                }
                else
                System.out.println("Error Fatal: no lo encontro el prodcuto\n");
            }
            float total =  Float.parseFloat(jLabelTotal.getText());
            tablaFactura.setRowCount(0);
            String nombreInsumo = "Error";
            int fila=0;
            for(DetalleVenta dv : factura){
                tablaFactura.addRow(new Object[3]);
                for(Producto p: productos){
                    if(p.getId() == dv.getIdInsumo()){
                        nombreInsumo = p.getNombre();
                        break;
                    }
                    else
                    System.out.println("Error Fatal, no se encontro el insumo\n");
                }
                jTableFactura.setValueAt(nombreInsumo,fila,0);
                jTableFactura.setValueAt(dv.getCantidad(), fila,1);
                jTableFactura.setValueAt(dv.getSubtotal(), fila,2);
                total -= dv.getSubtotal();
            }
            jLabelTotal.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_jButtonQuitarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        //Hay otra forma de hacerlo sin llamar a la base de datos
        productos.removeAll(productos);
        limpiar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAgregarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarFacturaActionPerformed
        if(jTableProductos.getSelectedRow() != -1){
            int stock = (int) jTableProductos.getValueAt(jTableProductos.getSelectedRow(),3);
            int cantidadPedida = (int) jTableProductos.getValueAt(jTableProductos.getSelectedRow(),4);
            if(cantidadPedida <= stock){
                Iterator<Producto> it = productos.iterator();
                Producto producto = new Producto();
                while(it.hasNext()){
                    //Ver si no se salta el primero
                    producto = it.next();
                    //Ver si modifica el iterator
                    if(producto.getId() == idProducto){
                        producto.setStock(stock - cantidadPedida);
                        break;
                    }
                    else
                    System.out.println("Error Fatal: no lo encontro el prodcuto\n");
                }
                DetalleVenta detalleVenta = new DetalleVenta();
                detalleVenta.setCantidad(cantidadPedida);
                detalleVenta.setIdInsumo(producto.getId());
                detalleVenta.setSubtotal(producto.getPrecio()*cantidadPedida);
                factura.add(detalleVenta);

                tablaProductos.setRowCount(0);
                String nombreInsumo = "Error";
                int fila=0;
                float total =  (float)0.0;
                for(DetalleVenta dv : factura){
                    tablaFactura.addRow(new Object[3]);
                    for(Producto p: productos){
                        if(p.getId() == dv.getIdInsumo()){
                            nombreInsumo = p.getNombre();
                            break;
                        }
                        else
                        System.out.println("Error Fatal, no se encontro el insumo\n");
                    }
                    jTableFactura.setValueAt(nombreInsumo,fila,0);
                    jTableFactura.setValueAt(dv.getCantidad(), fila,1);
                    jTableFactura.setValueAt(dv.getSubtotal(), fila,2);
                    total += dv.getSubtotal();
                }
                jLabelTotal.setText(String.valueOf(total));
            }
        }
    }//GEN-LAST:event_jButtonAgregarFacturaActionPerformed

    private void jTextFieldBuscarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarProductoKeyPressed
        tablaProductos.setRowCount(0);
        productos = vc.obtenerTodo();

        String buscar = jTextFieldBuscarProducto.getText();
        buscar = buscar.toUpperCase();
        int i;
        int fila = 0;
        for (Producto p : productos){
            String buscando = p.getNombre();
            buscando=buscando.toUpperCase();
            buscando = buscando.toUpperCase();

            if(buscando.contains(buscar)){
                tablaProductos.addRow(new Object[4]);
                jTableProductos.setValueAt(p.getId(),fila,0);
                jTableProductos.setValueAt(p.getNombre(),fila,1);
                jTableProductos.setValueAt(p.getPrecio(),fila,2);
                jTableProductos.setValueAt(p.getStock(), fila,3);
                fila++;
            }
        }
    }//GEN-LAST:event_jTextFieldBuscarProductoKeyPressed

    private void jTextFieldBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarProductoActionPerformed

    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked
        idProducto = (int) jTableProductos.getValueAt(jTableProductos.getSelectedRow(),0);
    }//GEN-LAST:event_jTableProductosMouseClicked

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        if(reparacion != null){
            this.mController.obtenerReparacion(reparacion.getId());
        }
    }//GEN-LAST:event_jPanel1ComponentShown

    private void jTextF1GestionRepBuscarEquiposKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextF1GestionRepBuscarEquiposKeyPressed
        // TODO add your handling code here:
        modeloTablaSeleccionarPresupuestos.setRowCount(0);

        String buscado;
        buscado=jTextF1GestionRepBuscarEquipos.getText();
        buscado = buscado.toUpperCase();
        int i;
        int fila =0;
        for (Equipo e : equipos){
            String buscando;
            buscando = e.getModelo();
            buscando=buscando.toUpperCase();

            if(buscando.contains(buscado)){
                modeloTablaSeleccionarPresupuestos.addRow(new Object[5]);
                jTableGestRepEquiposParaReparar.setValueAt(e.getModelo(),fila,0);
                jTableGestRepEquiposParaReparar.setValueAt(e.getMarca(),fila,1);
                jTableGestRepEquiposParaReparar.setValueAt(e.getFechaRecepcion(),fila,2);
                jTableGestRepEquiposParaReparar.setValueAt(e.getEstado(),fila,3);
                jTableGestRepEquiposParaReparar.setValueAt(e.getId(),fila,4);
                fila++;
            }

        }
    }//GEN-LAST:event_jTextF1GestionRepBuscarEquiposKeyPressed

    private void jTextF1GestionRepBuscarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextF1GestionRepBuscarEquiposActionPerformed

    }//GEN-LAST:event_jTextF1GestionRepBuscarEquiposActionPerformed

    private void jTextF1GestionRepBuscarEquiposMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextF1GestionRepBuscarEquiposMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextF1GestionRepBuscarEquiposMouseReleased

    private void jTextF1GestionRepBuscarEquiposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextF1GestionRepBuscarEquiposMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextF1GestionRepBuscarEquiposMouseExited

    private void jTextF1GestionRepBuscarEquiposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextF1GestionRepBuscarEquiposMouseEntered
        // TODO add your handling code here
        jTextF1GestionRepBuscarEquipos.setText("");
    }//GEN-LAST:event_jTextF1GestionRepBuscarEquiposMouseEntered

    private void jTextF1GestionRepBuscarEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextF1GestionRepBuscarEquiposMouseClicked
        // TODO add your handling code here:
        jTextF1GestionRepBuscarEquipos.setText("");
    }//GEN-LAST:event_jTextF1GestionRepBuscarEquiposMouseClicked

    private void jTextF2FallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextF2FallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextF2FallaActionPerformed

    private void jButtonAltaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaTareaActionPerformed
        // TODO add your handling code here:
        AltaTarea altTarea= new AltaTarea(this,reparacion.getEquipo().getId());
        altTarea.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAltaTareaActionPerformed

    private void jTableGestRepEquiposParaRepararMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGestRepEquiposParaRepararMouseClicked
        /*
        Integer codigoOrden = Integer.parseInt(String.valueOf(modeloTablaOrdenesPendientes.getValueAt(jTable2_TablaOrdenesPendientes.getSelectedRow(), 0)));
        System.out.println("Recibi el codigo de la orden numero: " + codigoOrden);
        modeloTablaAnalisisResultados.setRowCount(0);
        cargarTablaAnalisisResultado(codigoOrden);
        */
        //primero capturo el identificador del presupuesto en la tabla que fue clikeado
        Integer id= Integer.parseInt(String.valueOf(modeloTablaSeleccionarPresupuestos.getValueAt(jTableGestRepEquiposParaReparar.getSelectedRow(),4)));
        //con el id debo hacer una consulta y cargar los campos, enviando el presupuesto al view
        //this.mController.obtenerPresupuesto(idPresupuesto);
        System.out.println("entro a mouse clicked");
        jButtonAltaTarea.setEnabled(true);
        this.mController.obtenerReparacion(id);
    }//GEN-LAST:event_jTableGestRepEquiposParaRepararMouseClicked

    private void jTableGestRepEquiposParaReparar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGestRepEquiposParaReparar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableGestRepEquiposParaReparar1MouseClicked

    private void jTableGestRepEquiposParaReparar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGestRepEquiposParaReparar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableGestRepEquiposParaReparar2MouseClicked

    private void jTextF2Falla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextF2Falla1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextF2Falla1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarFactura;
    private javax.swing.JButton jButtonAltaTarea;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminarTarea;
    private javax.swing.JButton jButtonFinalizarReparacion;
    private javax.swing.JButton jButtonModificarTarea;
    private javax.swing.JButton jButtonQuitar;
    private javax.swing.JButton jButtonVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFechaIngreso;
    public javax.swing.JLabel jLabelFechaIngreso1;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelFactura;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JPanel jPanelVenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableFactura;
    private javax.swing.JTable jTableGestRepEquiposParaReparar;
    public javax.swing.JTable jTableGestRepEquiposParaReparar1;
    public javax.swing.JTable jTableGestRepEquiposParaReparar2;
    private javax.swing.JTable jTableGestRepListadoTareasSeleccionadas;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextF1GestionRepBuscarEquipos;
    private javax.swing.JTextField jTextF2Falla;
    public javax.swing.JTextField jTextF2Falla1;
    private javax.swing.JTextField jTextFMarca;
    public javax.swing.JTextField jTextFMarca1;
    private javax.swing.JTextField jTextFModelo;
    public javax.swing.JTextField jTextFModelo1;
    private javax.swing.JTextField jTextFiEstadoEquipo;
    public javax.swing.JTextField jTextFiEstadoEquipo1;
    private javax.swing.JTextField jTextFiEstadoRecepcionEqui;
    public javax.swing.JTextField jTextFiEstadoRecepcionEqui1;
    private javax.swing.JTextField jTextFieldBuscarProducto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarTablaGestRepEquiposParaReparar(List presupuestos) {
      
    }

    @Override
    public void mostrarTablaGestRepListadoTareasSeleccionadas(Reparacion reparacion) {
        
    }

    @Override
    public void mostrarCamposReparacion(Reparacion reparacion) {
        this.reparacion = reparacion;
        Equipo e = reparacion.getEquipo();
        jTextFiEstadoEquipo.setText(String.valueOf(e.getEstado()));
        jTextFMarca.setText(e.getMarca());
        jTextFModelo.setText(e.getModelo());
        jTextF2Falla.setText(e.getMotivoFalla());
        jTextFiEstadoRecepcionEqui.setText(e.getDetallesIngreso());
        jLabelFechaIngreso.setText(Funciones.dateFormat(e.getFechaRecepcion()));
        DefaultTableModel model = (DefaultTableModel) jTableGestRepListadoTareasSeleccionadas.getModel();
        model.setRowCount(0);
        for(Tarea t : reparacion.getTareas()){
            System.out.println("for tareas de la reparacion");
            Object[] nuevaTarea = {t.getNombre(),String.valueOf(t.getGarantia()),t.getDescripcion()};
            model.addRow(nuevaTarea);
        }
        
    }
    public void limpiar(){
        productos = vc.obtenerTodo();
        tablaProductos.setRowCount(0);
        int fila = 0;
        for(Producto p: productos){
            tablaProductos.addRow(new Object[4]);
            jTableProductos.setValueAt(p.getId(),fila,0);
            jTableProductos.setValueAt(p.getNombre(),fila,1);
            jTableProductos.setValueAt(p.getPrecio(),fila,2);
            jTableProductos.setValueAt(p.getStock(), fila,3);
            fila++;
        }
        
        factura.removeAll(factura);
        tablaFactura.setRowCount(0);
        jLabelTotal.setText("0.0");
    }

    @Override
    public void buscarProducto() {
       
    }

    @Override
    public void mostrarExito() {
        int resp = JOptionPane.showConfirmDialog(null, "La tarea se agrego con exito.", "EXITO",JOptionPane.OK_OPTION,JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void mostrarError(String text) {
        JOptionPane.showMessageDialog(null, text, "ERROR",JOptionPane.INFORMATION_MESSAGE);
    }
}
